# cotire.cmake 1.7.9 generated file
# /Users/yuma/github/BNNonFPGA/tiny-dnn/examples/example_caffe_converter_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/Users/yuma/github/BNNonFPGA/tiny-dnn/cmake/Modules/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.9")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELEASE "DNN_USE_IMAGE_API;CNN_USE_SSE;CNN_USE_AVX;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_RELEASE "-pthread;-msse3;-mavx;-Wall;-Wpedantic;-Wno-narrowing;-msse3;-mavx;-Wall;-Wpedantic;-Wno-narrowing;-O3;-O3;-std=gnu++14")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Release")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/Users/yuma/github/BNNonFPGA/tiny-dnn")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_RELEASE "/usr/local/include;$<BUILD_INTERFACE:/Users/yuma/github/BNNonFPGA/tiny-dnn>;$<INSTALL_INTERFACE:include/tiny_dnn>")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "caffe_converter/caffe_converter.cpp;/Users/yuma/github/BNNonFPGA/tiny-dnn/tiny_dnn/io/caffe/caffe.pb.cc")
set (COTIRE_TARGET_UNITY_DEPENDS "/Users/yuma/github/BNNonFPGA/tiny-dnn/tiny_dnn/io/caffe/caffe.pb.cc")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "Release")
set (CMAKE_CXX_COMPILER_ID "AppleClang")
set (CMAKE_CXX_COMPILER_VERSION "8.1.0.8020042")
set (CMAKE_CXX_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_FRAMEWORK_SEARCH_FLAG "-F")
set (CMAKE_CXX_SYSTEM_FRAMEWORK_SEARCH_FLAG "-iframework ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
